name: openhabittracker
version: '1.0.0'
grade: devel
summary: Take notes, plan tasks, track habits
description: |
  - Free and Ad-Free
  - Open Source
  - Privacy Focused: All user data is stored locally on your device
  - Available on Windows, Linux, Android, iOS, macOS, and as a web app
  - Localized to English, German, Spanish, Slovenian
  
  Key Features:
  
  - Markdown support for notes
  - Use categories and priorities to organize your notes, tasks, and habits
  - Advanced Search, Filter, and Sort
  - Data Export/Import: JSON, YAML, TSV, Markdown
  - Import your notes from Google Keep
  - Available in 26 themes with Dark and Light modes

base: core22

confinement: devmode

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

parts:
  openhabittracker:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: ./OpenHabitTracker.Blazor.Photino
    override-build: |
     dotnet build OpenHabitTracker.Blazor.Photino.csproj -c Release
     dotnet publish OpenHabitTracker.Blazor.Photino.csproj -r linux-x64 -c Release -p:PublishSingleFile=true --self-contained true -f net8.0 -o $SNAPCRAFT_PART_INSTALL
     chmod 0755 $SNAPCRAFT_PART_INSTALL/OpenHT
    build-packages:
      - libwebkit2gtk-4.1-dev
      - dotnet-sdk-8.0
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libicu70

apps:
  openhabittracker:
    command: OpenHT
